name: socibip
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  cloud_firestore: ^4.4.0
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  flutter_riverpod: ^2.2.0
  fpdart: ^0.4.0
  routemaster: ^1.0.1

  dotted_border: ^2.0.0+2
  file_picker: ^5.2.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  any_link_preview: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
    - assets/images/awards/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
