// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t_Hm9iXDUrhYkH2zluBnLeYiiwdLgFA',
    appId: '1:700834286043:web:0e58940fec14e6c331bffe',
    messagingSenderId: '700834286043',
    projectId: 'socibip',
    authDomain: 'socibip.firebaseapp.com',
    storageBucket: 'socibip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTW4z5SRBb471KLsnRmxUfBmbtGeUriVA',
    appId: '1:700834286043:android:abeda9e4a549bec231bffe',
    messagingSenderId: '700834286043',
    projectId: 'socibip',
    storageBucket: 'socibip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTEokOWW0Xv8jvxvvv7p6KjgLBcYv_Uv4',
    appId: '1:700834286043:ios:80364eeea1edf7e531bffe',
    messagingSenderId: '700834286043',
    projectId: 'socibip',
    storageBucket: 'socibip.appspot.com',
    iosClientId: '700834286043-139ijm381tn6jpj2qhmm5vrdvchki3lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.socibip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTEokOWW0Xv8jvxvvv7p6KjgLBcYv_Uv4',
    appId: '1:700834286043:ios:80364eeea1edf7e531bffe',
    messagingSenderId: '700834286043',
    projectId: 'socibip',
    storageBucket: 'socibip.appspot.com',
    iosClientId: '700834286043-139ijm381tn6jpj2qhmm5vrdvchki3lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.socibip',
  );
}
